/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as SamediRouteImport } from './routes/samedi'
import { Route as RepetiteursRouteImport } from './routes/repetiteurs'
import { Route as PolitiqueDeConfidentialiteRouteImport } from './routes/politique-de-confidentialite'
import { Route as PaiementRouteImport } from './routes/paiement'
import { Route as OffreRouteImport } from './routes/offre'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminStatistiquesRouteImport } from './routes/admin/statistiques'
import { Route as AdminInscriptionsRouteImport } from './routes/admin/inscriptions'

const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const SamediRoute = SamediRouteImport.update({
  id: '/samedi',
  path: '/samedi',
  getParentRoute: () => rootRouteImport,
} as any)
const RepetiteursRoute = RepetiteursRouteImport.update({
  id: '/repetiteurs',
  path: '/repetiteurs',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueDeConfidentialiteRoute =
  PolitiqueDeConfidentialiteRouteImport.update({
    id: '/politique-de-confidentialite',
    path: '/politique-de-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const PaiementRoute = PaiementRouteImport.update({
  id: '/paiement',
  path: '/paiement',
  getParentRoute: () => rootRouteImport,
} as any)
const OffreRoute = OffreRouteImport.update({
  id: '/offre',
  path: '/offre',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStatistiquesRoute = AdminStatistiquesRouteImport.update({
  id: '/admin/statistiques',
  path: '/admin/statistiques',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInscriptionsRoute = AdminInscriptionsRouteImport.update({
  id: '/admin/inscriptions',
  path: '/admin/inscriptions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/offre': typeof OffreRoute
  '/paiement': typeof PaiementRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/repetiteurs': typeof RepetiteursRoute
  '/samedi': typeof SamediRoute
  '/tarifs': typeof TarifsRoute
  '/admin/inscriptions': typeof AdminInscriptionsRoute
  '/admin/statistiques': typeof AdminStatistiquesRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/offre': typeof OffreRoute
  '/paiement': typeof PaiementRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/repetiteurs': typeof RepetiteursRoute
  '/samedi': typeof SamediRoute
  '/tarifs': typeof TarifsRoute
  '/admin/inscriptions': typeof AdminInscriptionsRoute
  '/admin/statistiques': typeof AdminStatistiquesRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/contact': typeof ContactRoute
  '/offre': typeof OffreRoute
  '/paiement': typeof PaiementRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/repetiteurs': typeof RepetiteursRoute
  '/samedi': typeof SamediRoute
  '/tarifs': typeof TarifsRoute
  '/admin/inscriptions': typeof AdminInscriptionsRoute
  '/admin/statistiques': typeof AdminStatistiquesRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/offre'
    | '/paiement'
    | '/politique-de-confidentialite'
    | '/repetiteurs'
    | '/samedi'
    | '/tarifs'
    | '/admin/inscriptions'
    | '/admin/statistiques'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/contact'
    | '/offre'
    | '/paiement'
    | '/politique-de-confidentialite'
    | '/repetiteurs'
    | '/samedi'
    | '/tarifs'
    | '/admin/inscriptions'
    | '/admin/statistiques'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/contact'
    | '/offre'
    | '/paiement'
    | '/politique-de-confidentialite'
    | '/repetiteurs'
    | '/samedi'
    | '/tarifs'
    | '/admin/inscriptions'
    | '/admin/statistiques'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ContactRoute: typeof ContactRoute
  OffreRoute: typeof OffreRoute
  PaiementRoute: typeof PaiementRoute
  PolitiqueDeConfidentialiteRoute: typeof PolitiqueDeConfidentialiteRoute
  RepetiteursRoute: typeof RepetiteursRoute
  SamediRoute: typeof SamediRoute
  TarifsRoute: typeof TarifsRoute
  AdminInscriptionsRoute: typeof AdminInscriptionsRoute
  AdminStatistiquesRoute: typeof AdminStatistiquesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samedi': {
      id: '/samedi'
      path: '/samedi'
      fullPath: '/samedi'
      preLoaderRoute: typeof SamediRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repetiteurs': {
      id: '/repetiteurs'
      path: '/repetiteurs'
      fullPath: '/repetiteurs'
      preLoaderRoute: typeof RepetiteursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-de-confidentialite': {
      id: '/politique-de-confidentialite'
      path: '/politique-de-confidentialite'
      fullPath: '/politique-de-confidentialite'
      preLoaderRoute: typeof PolitiqueDeConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paiement': {
      id: '/paiement'
      path: '/paiement'
      fullPath: '/paiement'
      preLoaderRoute: typeof PaiementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offre': {
      id: '/offre'
      path: '/offre'
      fullPath: '/offre'
      preLoaderRoute: typeof OffreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/statistiques': {
      id: '/admin/statistiques'
      path: '/admin/statistiques'
      fullPath: '/admin/statistiques'
      preLoaderRoute: typeof AdminStatistiquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inscriptions': {
      id: '/admin/inscriptions'
      path: '/admin/inscriptions'
      fullPath: '/admin/inscriptions'
      preLoaderRoute: typeof AdminInscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ContactRoute: ContactRoute,
  OffreRoute: OffreRoute,
  PaiementRoute: PaiementRoute,
  PolitiqueDeConfidentialiteRoute: PolitiqueDeConfidentialiteRoute,
  RepetiteursRoute: RepetiteursRoute,
  SamediRoute: SamediRoute,
  TarifsRoute: TarifsRoute,
  AdminInscriptionsRoute: AdminInscriptionsRoute,
  AdminStatistiquesRoute: AdminStatistiquesRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
